database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306
  user: bar
  password: password

mongodb:
  mongoURI: mongodb://localhost:27017
  databaseName: iot_platform
  collectionName: iot_updates
