name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt

      - name: Install MySQL
        run: sudo apt-get update && sudo apt-get install -y mysql-server

      - name: Start MySQL service
        run: sudo systemctl start mysql

      - name: Set up MySQL user and grant privileges
        run: |
          sudo mysql -u root -p "password" -e "CREATE USER 'bar'@'localhost' IDENTIFIED BY 'password';"
          sudo mysql -u root -p "password" -e "GRANT ALL PRIVILEGES ON *.* TO 'bar'@'localhost';"
          sudo mysql -u root -p "password" -e "FLUSH PRIVILEGES;"

      - name: Set up Gradle
        run: chmod +x gradlew
      - run: ./gradlew wrapper --gradle-version 6.7.1

      - name: Gradle build and run tests
        run: ./gradlew build
