name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: bar
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt

      - name: Set up Gradle
        run: chmod +x gradlew
      - run: ./gradlew wrapper --gradle-version 6.7.1

      - name: Gradle Build and run tests
        run: ./gradlew build
